 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/meetups", type: :request do
  # Meetup. As you add validations to Meetup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Meetup.create! valid_attributes
      get meetups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      meetup = Meetup.create! valid_attributes
      get meetup_url(meetup)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_meetup_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      meetup = Meetup.create! valid_attributes
      get edit_meetup_url(meetup)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Meetup" do
        expect {
          post meetups_url, params: { meetup: valid_attributes }
        }.to change(Meetup, :count).by(1)
      end

      it "redirects to the created meetup" do
        post meetups_url, params: { meetup: valid_attributes }
        expect(response).to redirect_to(meetup_url(Meetup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Meetup" do
        expect {
          post meetups_url, params: { meetup: invalid_attributes }
        }.to change(Meetup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post meetups_url, params: { meetup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested meetup" do
        meetup = Meetup.create! valid_attributes
        patch meetup_url(meetup), params: { meetup: new_attributes }
        meetup.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the meetup" do
        meetup = Meetup.create! valid_attributes
        patch meetup_url(meetup), params: { meetup: new_attributes }
        meetup.reload
        expect(response).to redirect_to(meetup_url(meetup))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        meetup = Meetup.create! valid_attributes
        patch meetup_url(meetup), params: { meetup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested meetup" do
      meetup = Meetup.create! valid_attributes
      expect {
        delete meetup_url(meetup)
      }.to change(Meetup, :count).by(-1)
    end

    it "redirects to the meetups list" do
      meetup = Meetup.create! valid_attributes
      delete meetup_url(meetup)
      expect(response).to redirect_to(meetups_url)
    end
  end
end
